// resources/assets/js/vue/components/Packages.vue
<template>
    <div>
        <h1>{{ type }} packages by Spatie</h1>
        <ul class="list-reset">
            <li v-for="p in packages" :key="p.id">
                <a
                    :href="p.url"
                    class="block no-underline bg-white p-6 mb-4 rounded-sm shadow border border-grey-lightest hover:border-grey-lighter"
                    target="_blank"
                >
                    <h2 class="text-base text-gold uppercase mb-1">
                        {{ p.name }}
                    </h2>
                    <div
                        v-html="p.description"
                        class="text-sm text-grey-darker"
                    ></div>
                </a>
            </li>
        </ul>
    </div>
</template>

<script>
import sortBy from 'lodash/sortBy';

export default {
    computed: {
        type() {
            return this.$route.params.type;
        },

        packages() {
            const packages = this.$store.getters.packagesWithType(this.type);

            return sortBy(packages, 'name');
        },
    },
};
</script>

// resources/assets/js/react/components/Packages.js
import React from 'react';
import { sortBy } from 'lodash';

function packageList(packages) {
    return sortBy(packages, 'name').map(p => (
        <li key={p.id}>
            <a
                href={p.url}
                className="block no-underline bg-white p-6 mb-4 rounded-sm shadow border border-grey-lightest hover:border-grey-lighter"
                target="_blank"
            >
                <h2 className="text-base text-gold uppercase mb-1">{p.name}</h2>
                <div
                    className="text-sm text-grey-darker"
                    dangerouslySetInnerHTML={{ __html: p.description }}
                />
            </a>
        </li>
    ));
}

const Packages = ({ match, packages }) => {
    const type = match.params.type;
    const listPackages = packages.filter(p => p.type === type);

    return (
        <div>
            <h1>{type} packages by Spatie</h1>
            <ul className="list-reset">{packageList(listPackages)}</ul>
        </div>
    );
};
export default Packages;
